export const POKEMON_TYPES_COLORS = {
  grass: 'bg-pokemon-grass',
  poison: 'bg-pokemon-poison',
  fire: 'bg-pokemon-fire',
  flying: 'bg-pokemon-flying',
  water: 'bg-pokemon-water',
  bug: 'bg-pokemon-bug',
  normal: 'bg-pokemon-normal',
  electric: 'bg-pokemon-electric',
  ground: 'bg-pokemon-ground',
  fighting: 'bg-pokemon-fighting',
  psychic: 'bg-pokemon-psychic',
  rock: 'bg-pokemon-rock',
  fairy: 'bg-pokemon-fairy',
  steel: 'bg-pokemon-steel',
  ice: 'bg-pokemon-ice',
  ghost: 'bg-pokemon-ghost',
  dragon: 'bg-pokemon-dragon',
  dark: 'bg-pokemon-dark'
} as const;
